version: '3.9'
name: socialnet-mongo

services:
  # First Shard Cluster
  mongoshard11:
    build:
      context: deploy/mongo/build/replicaset
    container_name: mongoshard11
    depends_on:
      - mongoshard12
      - mongoshard13
    command: mongod --shardsvr --replSet shard1 --dbpath /data/db --port 27017
    environment:
      - REPLICA_SET=shard1
    expose:
      - "27017"
    volumes:
      - shard_d11:/data/db
    networks:
      - socialnet
  mongoshard12:
    image: mongo
    container_name: mongoshard12
    command: mongod --shardsvr --replSet shard1 --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - shard_d12:/data/db
    networks:
      - socialnet
  mongoshard13:
    image: mongo
    container_name: mongoshard13
    command: mongod --shardsvr --replSet shard1 --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - shard_d13:/data/db
    networks:
      - socialnet

  # Second Shard Cluster
  mongoshard21:
    build:
      context: deploy/mongo/build/replicaset
    container_name: mongoshard21
    depends_on:
      - mongoshard22
      - mongoshard23
    command: mongod --shardsvr --replSet shard2 --dbpath /data/db --port 27017
    environment:
      - REPLICA_SET=shard2
    expose:
      - "27017"
    volumes:
      - shard_d21:/data/db
    networks:
      - socialnet
  mongoshard22:
    image: mongo
    container_name: mongoshard22
    command: mongod --shardsvr --replSet shard2 --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - shard_d22:/data/db
    networks:
      - socialnet
  mongoshard23:
    image: mongo
    container_name: mongoshard23
    command: mongod --shardsvr --replSet shard2 --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - shard_d23:/data/db
    networks:
      - socialnet

  # Config Cluster
  mongocfg1:
    build:
      context: deploy/mongo/build/replicaset
    container_name: mongocfg1
    depends_on:
      - mongocfg2
      - mongocfg3
    command: mongod --configsvr --replSet cfg --dbpath /data/db --port 27017
    environment:
      - REPLICA_SET=cfg
    expose:
      - "27017"
    volumes:
      - shard_c1:/data/db
    networks:
      - socialnet
  mongocfg2:
    image: mongo
    container_name: mongocfg2
    command: mongod --configsvr --replSet cfg --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - shard_c2:/data/db
    networks:
      - socialnet
  mongocfg3:
    image: mongo
    container_name: mongocfg3
    command: mongod --configsvr --replSet cfg --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - shard_c3:/data/db
    networks:
      - socialnet

  # Build mongos Router
  mongos1:
    build:
      context: deploy/mongo/build/router
    container_name: mongos1
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
      - mongoshard11
      - mongoshard12
      - mongoshard13
      - mongoshard21
      - mongoshard22
      - mongoshard23
    command: mongos --configdb cfg/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017 --bind_ip_all
    environment: #we can specify only the primary node for each cluster shard, other nodes will appear automatically
      - SHARDS=shard1/mongoshard11;shard2/mongoshard21
    ports:
      - 27017:27017
    expose:
      - "27017"
    networks:
      - socialnet

networks:
  socialnet:
    driver: bridge

volumes:
  shard_d11:
  shard_d12:
  shard_d13:
  shard_d21:
  shard_d22:
  shard_d23:
  shard_c1:
  shard_c2:
  shard_c3:
