spring:
  application:
    name: User Service
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
          username: ${PGUSER}
          password: ${PGPASSWORD}
          driver-class-name: org.postgresql.Driver
        slave_1:
          url: jdbc:postgresql://${PGHOST_SLAVE_1}:${PGPORT}/${PGDATABASE}
          username: ${PGUSER}
          password: ${PGPASSWORD}
          driver-class-name: org.postgresql.Driver
        slave_2:
          url: jdbc:postgresql://${PGHOST_SLAVE_2}:${PGPORT}/${PGDATABASE}
          username: ${PGUSER}
          password: ${PGPASSWORD}
          driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
  batch:
    jdbc:
      initialize-schema: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:fallback-key-only-for-testing}
    tokenExpirationTime: 3600
    refreshTokenExpirationTime: 1209600000

logging:
  level:
    ru.webdl.otus.socialnetwork: INFO

---
spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      schema-locations: classpath:schema.sql,classpath:schema-dev.sql
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false

logging:
  level:
    ru.webdl.otus.socialnetwork: DEBUG
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    org.springframework.security: ERROR
    org.springframework.jdbc.core.JdbcTemplate: ERROR
