server.port: 8082

externals:
  user-service:
    url: http://localhost:8080/
    get-user-path: api/v1/public/user/get/{userId}

spring:
  application.name: Chat Service
  config.import: optional:file:.env[.properties]

logging:
  level:
    ru.webdl.otus.socialnetwork: INFO
