server.port: 8082

externals:
  user-service:
    url: http://localhost:8080/
    get-user-path: api/v1/public/user/get/{userId}

spring:
  application.name: Chat Service
  config.import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatdb
      auto-index-creation: true

logging:
  level:
    org.springframework.data.mongodb: INFO
    ru.webdl.otus.socialnetwork: INFO
