server.port: ${SERVICE_PORT:8080}

externals:
  user-service:
    url: ${USER_SERVICE_URL}
    get-user-path: api/v1/public/user/get/{userId}

spring:
  application.name: Chat Service
  config.import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

logging:
  level:
    org.springframework.data.mongodb: INFO
    ru.webdl.otus.socialnetwork: INFO
